# Generated by Django 5.2.11 on 2026-02-21 07:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ELECTRIC', 'Electric'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=20)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel_station', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('odometer_reading_km', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='fuel_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fuel_expenses', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, help_text='Associated trip (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_expenses', to='trips.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_expenses', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'fuel_expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-date'], name='fuel_expens_vehicle_795c8e_idx'), models.Index(fields=['-date'], name='fuel_expens_date_8b0c44_idx')],
            },
        ),
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('expense_type', models.CharField(choices=[('TOLL', 'Toll'), ('PARKING', 'Parking'), ('CLEANING', 'Cleaning'), ('INSURANCE', 'Insurance'), ('REGISTRATION', 'Registration'), ('FINE', 'Fine/Penalty'), ('TIRE_REPLACEMENT', 'Tire Replacement'), ('ACCESSORIES', 'Accessories'), ('OTHER', 'Other')], max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expense_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_other_expenses', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_expenses', to='trips.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_expenses', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'other_expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-date'], name='other_expen_vehicle_5cae11_idx'), models.Index(fields=['expense_type', '-date'], name='other_expen_expense_c336dc_idx')],
            },
        ),
    ]
