# Generated by Django 5.2.11 on 2026-02-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelexpense',
            name='expense_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='expense_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
