# Generated by Django 5.2.11 on 2026-02-21 07:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(blank=True)),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('license_type', models.CharField(help_text='License category (e.g., CDL-A, CDL-B, Class C)', max_length=20)),
                ('license_expiry_date', models.DateField(db_index=True)),
                ('license_state', models.CharField(max_length=50)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('ON_DUTY', 'On Duty'), ('OFF_DUTY', 'Off Duty'), ('ON_TRIP', 'On Trip'), ('SUSPENDED', 'Suspended')], db_index=True, default='OFF_DUTY', max_length=20)),
                ('safety_score', models.IntegerField(default=100, help_text='Safety score out of 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_trips_completed', models.IntegerField(default=0)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['driver_id'],
                'indexes': [models.Index(fields=['status', 'license_expiry_date'], name='drivers_status_d8f98b_idx'), models.Index(fields=['-created_at'], name='drivers_created_cd9a14_idx')],
            },
        ),
    ]
