# Generated by Django 5.2.11 on 2026-02-21 07:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive Maintenance'), ('REPAIR', 'Repair'), ('INSPECTION', 'Inspection'), ('OIL_CHANGE', 'Oil Change'), ('TIRE_SERVICE', 'Tire Service'), ('BRAKE_SERVICE', 'Brake Service'), ('ENGINE_REPAIR', 'Engine Repair'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('service_provider', models.CharField(max_length=200)),
                ('technician_name', models.CharField(blank=True, max_length=100)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('odometer_reading_km', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, help_text='Service receipts, invoices, etc.', null=True, upload_to='maintenance_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'maintenance_records',
                'ordering': ['-scheduled_date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'status'], name='maintenance_vehicle_9785b7_idx'), models.Index(fields=['-scheduled_date'], name='maintenance_schedul_46e68d_idx')],
            },
        ),
    ]
