# Generated by Django 5.2.11 on 2026-02-21 07:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_address', models.TextField()),
                ('pickup_coordinates', models.CharField(blank=True, max_length=100)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_address', models.TextField()),
                ('dropoff_coordinates', models.CharField(blank=True, max_length=100)),
                ('cargo_description', models.TextField()),
                ('cargo_weight_kg', models.DecimalField(decimal_places=2, help_text='Cargo weight in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cargo_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cargo value', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('scheduled_pickup_time', models.DateTimeField()),
                ('scheduled_delivery_time', models.DateTimeField()),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_odometer_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('end_odometer_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='trips_status_81313c_idx'), models.Index(fields=['vehicle', 'status'], name='trips_vehicle_06cd2b_idx'), models.Index(fields=['driver', 'status'], name='trips_driver__f38efc_idx'), models.Index(fields=['scheduled_pickup_time'], name='trips_schedul_9a9a81_idx')],
            },
        ),
    ]
