# Generated by Django 5.2.11 on 2026-02-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
